import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";

const inter = localFont({
    src: "./fonts/Inter-VF.ttf",
    variable: "--font-inter",
    weight: "200 300 400 500 600 700 800 900",
});

const plexMono = localFont({
    src: "./fonts/JetBrainsMono-VF.ttf",
    variable: "--font-plex-mono",
    weight: "300 500 600 700 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${inter.variable} ${plexMono.variable} antialiased`}
            >
                <Providers>
                    {children}
                    <Toaster />
                </Providers>
            </body>
        </html>
    );
}
